[General]
    process_list = ["Producer", "Processor", "Consumer"]

[Producer]
    input_ip = "192.168.1.1"
    output_ip = "192.168.1.2"
    input_port = 8000
    output_port = 8001
    module_name = "producer_module"

[Processor]
    input_ip = "192.168.1.2"
    output_ip = "192.168.1.3"
    input_port = 8001
    output_port = 8002
    module_name = "processor_module"

[Consumer]
    input_ip = "192.168.1.3"
    output_ip = "192.168.1.4"
    input_port = 8002
    output_port = 8003
    module_name = "consumer_module"